#!/usr/bin/python3
'''
watchdog - monitor bellows + processes and restart if not responding
'''
import re
import select
import subprocess
import sys
import time
import requests
# regular expression patterns to look for
GATEWAY_PATTERN = re.compile(r'bellows gateway')
HTTPSERVER_PATTERN = re.compile(r'python ./httpserver.py')
TIMEDEVENTGENERATOR_PATTERN = re.compile(r'python ./timedEventGenerator.py')
TIME_WAIT_PATTERN = re.compile(r'TIME_WAIT')
ESTABLISHED_PATTERN = re.compile(r'ESTABLISHED')
# constants
RETRY_LIMIT = 3
FAIL_THRESHOLD = 3
HOLD_LIMIT = 3

def start_restart_gateway():
    '''
    start_restart_gateway - starts/restarts a child process that is the bellows + gateway
    '''
    print("starting/restarting bellows + gateway")
    return subprocess.Popen(['../../../bin/bellows', 'gateway'],
                            close_fds=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

def start_restart_httpserver():
    '''
    start_restart_httpserver - starts/restarts a child process that is the httpserver
    '''
    print("starting/restarting httpserver")
    return subprocess.Popen(['./httpserver.py'],
                            close_fds=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

def start_restart_timedEventGenerator():
    '''
    start_restart_timedEventGenerator - starts/restarts a child process that is
                                        the timedEventGenerator
    '''
    print("starting/restarting timedEventGenerator")
    return subprocess.Popen(['./timedEventGenerator.py'],
                            close_fds=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

def protected_command_line(command):
    '''
    protected_command_line - executes a command line, picks up the results, and handles errors
    '''
    ok = False
    retry = True
    count = 0
    result = ""
    while retry:
        try:
            result = subprocess.check_output(command, shell=True).decode("utf-8")
            ok = True
            retry = False
        except subprocess.CalledProcessError as err:
            print(f"called process error: {err}")
            time.sleep( 2 * count )
            count += 1
            ok = True
            if count > RETRY_LIMIT:
                retry = False
        except Exception as err:
            print(f"other exception: {err}")
            time.sleep( 2 * count )
            count += 1
            if count > RETRY_LIMIT:
                retry = False
                print("command returned error code:", err)

    if not ok:
        print("terminating")
        sys.exit(1)

    if count > 0:
        print("info: while executing command,", command, ", had to retry", count, "times")

    return result

def check_for_hung_server_template():
    '''
    check_for_hung_server - if HTTP connection is persistently present, server is likely hung
    '''
    httpserver_has_been_operational = 0
    httpserver_no_response_failure_count = 0
    hold = 0
    while True:
        (httpserver_has_been_operational, httpserver_no_response_failure_count) = yield (
            httpserver_has_been_operational, httpserver_no_response_failure_count)
        try:
            result = protected_command_line("/usr/bin/netstat -an | grep 8124")
            found = False
            for line in result.split("\n"):
                found = ESTABLISHED_PATTERN.search(line)
                if found:
                    break
            if not found:
                hold += 1
                if hold > HOLD_LIMIT:
                    hold = 0
                    print("sending a get")
                    requests.get('http://localhost:8124/index.html', timeout=5.0)
                    httpserver_has_been_operational = True
                    httpserver_no_response_failure_count = 0
            else:
                if httpserver_has_been_operational:
                    httpserver_no_response_failure_count += 1
                print("possible hung httpserver - current count: "
                      f"{httpserver_no_response_failure_count}")

        except requests.exceptions.Timeout:
            print("httpserver is not responding")
            if httpserver_has_been_operational:
                httpserver_no_response_failure_count += 1
        except requests.exceptions.ConnectionError:
            print("can not connect to httpserver")

def main():
    '''
    main program
    '''
    gateway_failure_count = 0
    httpserver_failure_count = 0
    httpserver_no_response_failure_count = 0
    timedEventGenerator_failure_count = 0
    processes = {}
    restarts = 0
    httpserver_has_been_operational = False
    check_for_hung_server = check_for_hung_server_template()
    next(check_for_hung_server)

    try:
        while True:  # don't stop
            result = protected_command_line("ps -ef | grep gateway 2>&1")
            for line in result.split("\n"):
                found = GATEWAY_PATTERN.search(line)
                if found:
                    gateway_failure_count = 0
                    break
                gateway_failure_count += 1
            result = protected_command_line("ps -ef | grep httpserver.py 2>&1")
            for line in result.split("\n"):
                found = HTTPSERVER_PATTERN.search(line)
                if found:
                    httpserver_failure_count = 0
                    break
                httpserver_failure_count += 1
            (httpserver_has_been_operational, httpserver_no_response_failure_count) = check_for_hung_server.send(
                (httpserver_has_been_operational, httpserver_no_response_failure_count))
            result = protected_command_line("ps -ef | grep timedEventGenerator.py 2>&1")
            for line in result.split("\n"):
                found = TIMEDEVENTGENERATOR_PATTERN.search(line)
                if found:
                    timedEventGenerator_failure_count = 0
                    break
                timedEventGenerator_failure_count += 1
            if gateway_failure_count > FAIL_THRESHOLD:
                restarts += 1
                processes['gateway'] = start_restart_gateway()
            if (httpserver_failure_count > FAIL_THRESHOLD or
                httpserver_no_response_failure_count > FAIL_THRESHOLD):
                restarts += 1
                httpserver_has_been_operational = False
                if 'httpserver' in processes:
                    processes['httpserver'].terminate()
                processes['httpserver'] = start_restart_httpserver()
                httpserver_no_response_failure_count = 0
            if timedEventGenerator_failure_count > FAIL_THRESHOLD:
                restarts += 1
                processes['timedEventGenerator'] = start_restart_timedEventGenerator()
            for _, process in processes.items():
                rlist, _, _ = select.select([process.stdout.fileno(),
                                             process.stderr.fileno()], [], [], 1.0)
                if process.stdout.fileno() in rlist:
                    process.stdout.readline()
                if process.stderr.fileno() in rlist:
                    process.stderr.readline()
            time.sleep(10)
    except KeyboardInterrupt:
        print(f"Terminating, total starts or restarts: {restarts}")
        for _, process in processes.items():
            process.terminate()

if __name__ == "__main__":
    if len(sys.argv) != 1:
        print("usage: watchdog")
        sys.exit(1)
    main()
